release: "github"
github:
  repo: "ngx-phone-validators"
  user: "nightapes"
commitFormat: angular
integrations:
  npm:
    enabled: true
branch:
  master: release
hooks:
  preRelease:
    - yarn build
    - echo //registry.npmjs.org/:_authToken=$NPM_TOKEN >> ~/.npmrc
    - yarn publish dist
    - rm ~/.npmrc
    - cat package.json | jq '.name = "@Nightapes/ngx-phone-validators"' >> package2.json && mv package2.json package.json
    - yarn config set registry https://npm.pkg.github.com/
    - echo "//npm.pkg.github.com/:_authToken=$GITHUB_PAT" >> ~/.npmrc
    - yarn publish dist
