release: "github"
github:
  repo: "ngx-phone-validators"
  user: "nightapes"
commitFormat: angular
integrations:
  npm:
    enabled: true
branch:
  master: release
hooks:
  preRelease:
    - yarn build
    - echo //registry.npmjs.org/:_authToken=$NPM_TOKEN >> ~/.npmrc
    - yarn publish dist
    - rm ~/.npmrc
    - yarn config set registry https://npm.pkg.github.com/@Nightapes/
    - echo "//npm.pkg.github.com/@Nightapes/:_authToken=$GITHUB_PAT" >> ~/.npmrc
    - yarn publish dist
