sudo: required
language: node_js
addons:
  chrome: stable
cache: yarn
notifications:
  email: false
node_js:
  - '8'
after_success:
  - yarn build
  - cp .git dist/.git/ -r # required by semantic release
  - cd dist
  - yarn install
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/