sudo: required
language: node_js
cache: yarn
addons:
  chrome: stable
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@3 # fix for https://github.com/npm/npm/issues/19222
after_success:
  - yarn build
  - cp .git dist/ -r # required by semantic release
  - cp README.md dist/
  - cd dist
  - yarn install
  - yarn semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
